df = read.table('D:\\OneDrive - zju.edu.cn\\Coursera\\R-4\\household_power_consumption.txt',
        sep = ';',header = TRUE)
df$FullTime <- strptime(paste(df$Date, df$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
df$Date = as.Date(df$Date,'%d/%m/%Y')
df = subset(df, Date >= as.Date('2007-02-01'))
df = subset(df, Date <= as.Date('2007-02-02'))
head(df)
df$Global_active_power = as.numeric(df$Global_active_power)
df$Sub_metering_1 = as.numeric(df$Sub_metering_1)
df$Sub_metering_2 = as.numeric(df$Sub_metering_2)
df$Sub_metering_3 = as.numeric(df$Sub_metering_3)
df$Voltage = as.numeric(df$Voltage)
df$Global_reactive_power = as.numeric(df$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(df$FullTime, df$Global_active_power, type = 'l',xlab = '', ylab= 'Global active power', main = '')
plot(df$FullTime, df$Voltage, type = 'l',xlab = 'datetime', ylab= 'Voltage', main = '')
with(df, plot(FullTime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
lines(df$FullTime, df$Sub_metering_2,col='red',type='l')
lines(df$FullTime, df$Sub_metering_3,col='blue',type='l')
legend(c("topright"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty= 1, lwd=2, col = c("black", "red", "blue"))
plot(df$FullTime, df$Global_reactive_power,type = 'l',xlab = 'datetime', ylab= 'Global_reactive_power', main = '')
dev.off()

